---
title: "R markdown test"
output: word_document 
  
---
## Chart 1
```{r echo=FALSE, warning=FALSE}
library(plotly)
library(tidyr)
library(raster)
library(weathermetrics)

GB_auto <- raster::getData('GADM', 
                           country="GBR", 
                           level=0, 
                           #set the path to store your data in
                           path='prac4_data/', 
                           download=TRUE)

GBclim <- raster::getData("worldclim", 
                          res=5, 
                          var="tmean",
                          #set the path to store your data in
                          path='prac4_data/', 
                          download=TRUE)

month <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
names(GBclim) <- month

GBtemp <- GBclim %>%
  crop(., GB_auto)%>%
  #WorldClim data has a scale factor of 10!
  mask(., GB_auto)/10

alldf <- GBtemp %>% 
  as.data.frame()%>%
  pivot_longer(
  cols = 1:12,
  names_to = "Month",
  values_to = "Temp")%>%
  drop_na()

jan<-filter(alldf, Month=="Jan")
jun<-filter(alldf, Month=="Jun")

# give axis titles
x <- list (title = "Temperature")
y <- list (title = "Frequency")

# set the bin width
xbinsno<-list(start=-5, end=20, size = 2.5)

# plot the histogram calling all the variables we just set
ihist<-plot_ly(alpha = 0.6) %>%
        add_histogram(x = jan$Temp,
        xbins=xbinsno, name="January") %>%
        add_histogram(x = jun$Temp,
        xbins=xbinsno, name="June") %>% 
        layout(barmode = "overlay", xaxis=x, yaxis=y)

ihist
```
Column {data-width=400}
-------------------------------------

### Chart 2
```{r}
x <- c(1:5); y <- x # create some data
par(pch=22, col="red") # plotting symbol and color
par(mfrow=c(2,4)) # all plots on one page
opts <-  c("p","l","o","b","c","s","S","h")
for(i in 1:length(opts)){
  heading = paste("type=",opts[i])
  plot(x, y, type="n", main=heading)
  lines(x, y, type=opts[i])
}
```

